# Generated by Django 3.2.8 on 2022-03-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamebit', '0002_alter_review_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(max_length=300),
        ),
    ]
